### ISSUE TITLE
pressing ctrl-C during a `list --pick` causes an exception

### ISSUE THREAD

**Issue by bluehood** [papis/papis#102]
ctrl-C is a natural way to quit the `list --pick` interactive menu in case I decide to not pick any document after all. This is what happens (papis v0.7.3):

```
~ papis list --pick             
....ctrl-C pressed....                                                                                                                                                                             (papis) 
Traceback (most recent call last):
  File "/home/eguiraud/Tools/miniconda2/envs/papis/bin/papis", line 11, in <module>
    sys.exit(main())
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/papis/main.py", line 22, in main
    papis.commands.default.run()
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/papis/commands/list.py", line 237, in cli
    template=template
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/papis/commands/list.py", line 149, in run
    document.get_main_folder() for document in documents
  File "/home/eguiraud/Tools/miniconda2/envs/papis/lib/python3.7/site-packages/papis/commands/list.py", line 149, in <listcomp>
    document.get_main_folder() for document in documents
AttributeError: 'NoneType' object has no attribute 'get_main_folder'
```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

**Comment by alejandrogallo** [comment]
Thanks! It is fixed now!
