### ISSUE TITLE
Error when using vim or dmenu as picktool

### ISSUE THREAD

**Issue by gokulsoumya** [papis/papis#118]
When the `picktool` option is set to `vim` or `dmenu`, there's an error:

With `vim`:

```shell
$ papis -v --debug edit
109-DEBUG:papis:DEBUG MODE FOR DEVELOPERS ON
109-DEBUG:papis:Imported commands
115-DEBUG:config:Merging configuration from /home/gokul/Documents/papers/.papis.config
117-DEBUG:db:cache:Initializing
149-DEBUG:cache:Getting documents from dir /home/gokul/Documents/papers
156-DEBUG:cache:Cache path = /home/gokul/.cache/papis/92eec8f5b67d596efb5c94a6b8dab80e-papers
157-DEBUG:cache:Loading folders from cache
161-DEBUG:cache:Getting cache /home/gokul/.cache/papis/92eec8f5b67d596efb5c94a6b8dab80e-papers 
162-DEBUG:db:cache:Loaded folders from cache (2 documents)
162-DEBUG:db:cache:Creating document objects
176-DEBUG:dir2doc:Running in 1 cores
210-DEBUG:dir2doc:pool started
412-DEBUG:dir2doc:pool done (200.81591796875 ms)
413-DEBUG:db:cache:Done
413-DEBUG:db:cache:Querying
475-DEBUG:query_parser:Parsing search
481-DEBUG:query_parser:Parsed query = []
482-DEBUG:api:Parsing picktool
484-DEBUG:api:Using vim picker
Traceback (most recent call last):
  File "/home/gokul/.local/bin/papis", line 11, in <module>
    sys.exit(main())
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/main.py", line 22, in main
    papis.commands.default.run()
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/commands/edit.py", line 65, in cli
    document = papis.api.pick_doc(documents)
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/api.py", line 104, in pick_doc
    pick_config
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/api.py", line 147, in pick
    return papis.gui.vim.pick(options, **pick_config)
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/gui/vim/main.py", line 46, in pick
    ret = options[int(index)-1]
ValueError: invalid literal for int() with base 10: "<red>GNU C reference manual</red>\n <span color='#00ff00'>Sandra Loosemore</span>\n  <span color='#00ffaa'>(2018)</span> [<yellow>programming</yellow>]\n<red>What Is New in LaTeX? VI. LaTeX on an iPa
```

In between, vim opens, and shows a message:

```
"/tmp/tmp6p6w5o3v" 7L, 375C                                                                                                    
Error detected while processing command line:
E484: Can't open file /home/gokul/.local/lib/python3.6/site-packages/papis/gui/vim/pick.vim
Press ENTER or type command to continue
```

With dmenu:

```shell
63-DEBUG:papis:DEBUG MODE FOR DEVELOPERS ON
64-DEBUG:papis:Imported commands
69-DEBUG:config:Merging configuration from /home/gokul/Documents/papers/.papis.config
71-DEBUG:db:cache:Initializing
93-DEBUG:cache:Getting documents from dir /home/gokul/Documents/papers
93-DEBUG:cache:Cache path = /home/gokul/.cache/papis/92eec8f5b67d596efb5c94a6b8dab80e-papers
93-DEBUG:cache:Loading folders from cache
101-DEBUG:cache:Getting cache /home/gokul/.cache/papis/92eec8f5b67d596efb5c94a6b8dab80e-papers 
103-DEBUG:db:cache:Loaded folders from cache (2 documents)
104-DEBUG:db:cache:Creating document objects
128-DEBUG:dir2doc:Running in 1 cores
144-DEBUG:dir2doc:pool started
346-DEBUG:dir2doc:pool done (200.89697265625 ms)
347-DEBUG:db:cache:Done
347-DEBUG:db:cache:Querying
408-DEBUG:query_parser:Parsing search
413-DEBUG:query_parser:Parsed query = []
414-DEBUG:api:Parsing picktool
417-DEBUG:api:Using dmenu picker
Traceback (most recent call last):
  File "/home/gokul/.local/lib/python3.6/site-packages/dmenu/dmenu.py", line 180, in show
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dmenu': 'dmenu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gokul/.local/bin/papis", line 11, in <module>
    sys.exit(main())
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/main.py", line 22, in main
    papis.commands.default.run()
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gokul/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/commands/edit.py", line 65, in cli
    document = papis.api.pick_doc(documents)
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/api.py", line 104, in pick_doc
    pick_config
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/api.py", line 143, in pick
    return papis.gui.dmenu.pick(options, **pick_config)
  File "/home/gokul/.local/lib/python3.6/site-packages/papis/gui/dmenu.py", line 45, in pick
    header = _dmenu_pick(headers)
  File "/home/gokul/.local/lib/python3.6/site-packages/dmenu/dmenu.py", line 183, in show
    raise DmenuCommandError(args, err)
dmenu.dmenu.DmenuCommandError: The provided dmenu command could not be used (['dmenu', '-b', '-i', '-l', '20', '-fn', 'monospace-14', '-nb', '#000000', '-nf', '#55ff55', '-sb', '#005500', '-sf', '#f0f0f0']): [Errno 2] No such file or directory: 'dmenu': 'dmenu'
```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/91 (vim/vimtex integration).

**Comment by alejandrogallo** [comment]
Hi!
Thanks for taking the time to report and sorry for the delay!
## For vim
You probably want to change the `header-format`, for instance in your `~/.config/papis/config` file
```ini
[settings]
picktool = vim
header-format = {doc[title]} {doc[author]}
```

## For dmenu
I think you don't have the `dmenu` program installed in your system, might this be the issue?

Cheers!

**Comment by gokulsoumya** [comment]
For vim, changing `header-format` fixed some of the formatting, but the `E484: Can't open file ....` error still occured. So I looked around a bit, and it seems `pick.vim` isn't in the `package_data` section in setup.py: 

https://github.com/papis/papis/blob/09af950866efdca82e6d7b142b76838def79b9e0/setup.py#L103-L107

I think this might be the problem; I copied the missing `pick.vim` to the vim directory of my installation of papis, and it worked fine.

And for `dmenu`, I do have it installed, so there might be something else that is causing the problem.

**Comment by alejandrogallo** [comment]
Thank you very much for pointing out the `pick.vim` bug, however I think we will erase in the future the
vim from papis and make a package out of it.

As for the `dmenu` problem, I don't know exactly why this is happening, for me it is working..

**Comment by gokulsoumya** [comment]
Sorry; I actually didn't have `dmenu` installed. It works fine after installing it. I should have checked it properly.

**Comment by alejandrogallo** [comment]
Dont worry, thank you for reporting and trying to make papis better. Happy reading!
