### ISSUE TITLE
whoosh backend how to export everything ?

### ISSUE THREAD

**Issue by teto** [papis/papis#158]
on master 9f578166d6d3b05d8cc182a10b5eff7f0d76821f, I can't export my library, here are the 2 errors:
```
(ins)[nix-shell:~/papis]$ papis -v export --all --bibtex
117-DEBUG:db:cache:Querying
119-DEBUG:db:cache:Getting documents from cache in /home/teto/.cache/papis/database/5b95a1a2ce149bd9e72f01dab58fd37e-papis_db
138-DEBUG:db:cache:Loaded documents (1092 documents)
155-DEBUG:query_parser:Parsing search
156-DEBUG:query_parser:Parsed query = [['*']]
177-DEBUG:filter:Filtering 1092 docs (search '*') using 4 cores
178-DEBUG:filter:pool started
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/teto/papis/papis/docmatcher.py", line 69, in return_if_match
    match = doc if cls.matcher(doc, search, sformat) else None
  File "/home/teto/papis/papis/database/cache.py", line 132, in match_document
    return re.match(regex, match_string, re.IGNORECASE)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_parse.py", line 654, in _parse
    source.tell() - here + len(this))
re.error: multiple repeat at position 2
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/user/1000/tmp.WN9GWbAalF/bin/papis", line 11, in <module>
    load_entry_point('papis', 'console_scripts', 'papis')()
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/83glni8a99pkal667qckk0ibb6rc0jca-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/teto/papis/papis/commands/export.py", line 179, in cli
    documents = papis.database.get().query(query)
  File "/home/teto/papis/papis/database/cache.py", line 242, in query
    return filter_documents(docs, query_string)
  File "/home/teto/papis/papis/database/cache.py", line 93, in filter_documents
    papis.docmatcher.DocMatcher.return_if_match, documents
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
re.error: multiple repeat at position 2

(ins)[nix-shell:~/papis]$ papis -v export --all --bibtex '*'
116-DEBUG:db:cache:Querying
116-DEBUG:db:cache:Getting documents from cache in /home/teto/.cache/papis/database/5b95a1a2ce149bd9e72f01dab58fd37e-papis_db
134-DEBUG:db:cache:Loaded documents (1092 documents)
148-DEBUG:query_parser:Parsing search
149-DEBUG:query_parser:Parsed query = []
161-DEBUG:filter:Filtering 1092 docs (search *) using 4 cores
162-DEBUG:filter:pool started
266-DEBUG:filter:done (104.167236328125 ms) (0 docs)
267-WARNING:cli:export:No documents retrieved
```
I really don't get why should I add '*' after `--all` ? it seems very counterintuitive.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/papis/papis/issues/31 (Update database model to allow for whoosh backend), https://github.com/papis/papis/issues/60 (Export multiple elements), https://github.com/alejandrogallo/papis/issues/20 (gracefully treat conflicting export config), and https://github.com/papis/papis/issues/134 (Exporting --to-bibtex is semi-broken).

**Comment by alejandrogallo** [comment]
Try

**Comment by teto** [comment]
I've updated and it now works with `papis -v export --all --bibtex '*'` while `.` won't. On the other hand  `papis update --delete date "*"` or `papis update --delete date "."` won't select any document :'(

**Comment by alejandrogallo** [comment]
Hi, I mean, it depends on the database you're using.
Whoosh uses wildcards, so `'*'` should match everything, the papis database uses regular expressions
and fuzzy finder, so actually `.` should match everything.

Since you've got `db:cache` and not whoosh going on, you should use `.`.
This really doesn't work?
If you do
```
papis --cc
papis  -v export --all --bibtex .
```
this doesn't work, clearing the cache?

**Comment by teto** [comment]
I am using the whoosh database. I've patched locally the whoosh backend so that it always does what I want (i.e., empty query selects all).

There is something I don't get though is why the update mechanism launches the picker ?
```

papis -v update --no-interactive --delete date "*"
269-DEBUG:db:whoosh:Initialized index found for library
269-DEBUG:db:whoosh:Query string *
829-DEBUG:db:whoosh:<Top 1090 Results for Or([Every('title', boost=1.0), Every('author', boost=1.0), Every('tags', boost=1.0)]) runtime=0.5526074910303578>
3890-DEBUG:tui:widget:list:processing 1090 options
3919-DEBUG:tui:widget:list:processing headers
4056-DEBUG:tui:widget:list:got 1090 headers
4056-DEBUG:tui:widget:list:processing matchers
4077-DEBUG:tui:widget:list:got 1090 matchers

```
then it launches the picker and doesn't remove the "date" entry :/
I saw this flag so I tried with `--no-interactive` to no avail.
```
@click.option(
    "-i/-b,--batch",
    "--interactive/--no-interactive",
    help="Interactive or batch mode",
    default=True
)

```
The -b flag seemed ineffective as well (is it supposed to do anything ?).
