### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by stasvlasov** [papis/papis#165]
First, thank you for developing papis. It is great!

I am trying to install it on Windows 10 without luck. This is what I get after running `pip install papis` in elevated (run as admin) cmd.exe

```
  Running setup.py install for papis ... error
    Complete output from command c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\svlasov\\AppData\\Local\\Temp\\pip-install-j3i5hbfq\\papis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\svlasov\AppData\Local\Temp\pip-record-l509184s\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\papis
    copying papis\api.py -> build\lib\papis
    copying papis\arxiv.py -> build\lib\papis
    copying papis\base.py -> build\lib\papis
    copying papis\bibtex.py -> build\lib\papis
    copying papis\cli.py -> build\lib\papis
    copying papis\config.py -> build\lib\papis
    copying papis\crossref.py -> build\lib\papis
    copying papis\dissemin.py -> build\lib\papis
    copying papis\docmatcher.py -> build\lib\papis
    copying papis\document.py -> build\lib\papis
    copying papis\exceptions.py -> build\lib\papis
    copying papis\isbn.py -> build\lib\papis
    copying papis\isbnplus.py -> build\lib\papis
    copying papis\main.py -> build\lib\papis
    copying papis\pick.py -> build\lib\papis
    copying papis\utils.py -> build\lib\papis
    copying papis\__init__.py -> build\lib\papis
    creating build\lib\papis\commands
    copying papis\commands\add.py -> build\lib\papis\commands
    copying papis\commands\addto.py -> build\lib\papis\commands
    copying papis\commands\browse.py -> build\lib\papis\commands
    copying papis\commands\config.py -> build\lib\papis\commands
    copying papis\commands\default.py -> build\lib\papis\commands
    copying papis\commands\edit.py -> build\lib\papis\commands
    copying papis\commands\explore.py -> build\lib\papis\commands
    copying papis\commands\export.py -> build\lib\papis\commands
    copying papis\commands\external.py -> build\lib\papis\commands
    copying papis\commands\git.py -> build\lib\papis\commands
    copying papis\commands\list.py -> build\lib\papis\commands
    copying papis\commands\mv.py -> build\lib\papis\commands
    copying papis\commands\open.py -> build\lib\papis\commands
    copying papis\commands\rename.py -> build\lib\papis\commands
    copying papis\commands\rm.py -> build\lib\papis\commands
    copying papis\commands\run.py -> build\lib\papis\commands
    copying papis\commands\update.py -> build\lib\papis\commands
    copying papis\commands\__init__.py -> build\lib\papis\commands
    creating build\lib\papis\database
    copying papis\database\base.py -> build\lib\papis\database
    copying papis\database\cache.py -> build\lib\papis\database
    copying papis\database\whoosh.py -> build\lib\papis\database
    copying papis\database\__init__.py -> build\lib\papis\database
    creating build\lib\papis\downloaders
    copying papis\downloaders\acs.py -> build\lib\papis\downloaders
    copying papis\downloaders\annualreviews.py -> build\lib\papis\downloaders
    copying papis\downloaders\aps.py -> build\lib\papis\downloaders
    copying papis\downloaders\arxiv.py -> build\lib\papis\downloaders
    copying papis\downloaders\base.py -> build\lib\papis\downloaders
    copying papis\downloaders\frontiersin.py -> build\lib\papis\downloaders
    copying papis\downloaders\get.py -> build\lib\papis\downloaders
    copying papis\downloaders\hal.py -> build\lib\papis\downloaders
    copying papis\downloaders\ieee.py -> build\lib\papis\downloaders
    copying papis\downloaders\iopscience.py -> build\lib\papis\downloaders
    copying papis\downloaders\libgen.py -> build\lib\papis\downloaders
    copying papis\downloaders\scitationaip.py -> build\lib\papis\downloaders
    copying papis\downloaders\thesesfr.py -> build\lib\papis\downloaders
    copying papis\downloaders\utils.py -> build\lib\papis\downloaders
    copying papis\downloaders\worldscientific.py -> build\lib\papis\downloaders
    copying papis\downloaders\__init__.py -> build\lib\papis\downloaders
    creating build\lib\papis\tui
    copying papis\tui\app.py -> build\lib\papis\tui
    copying papis\tui\utils.py -> build\lib\papis\tui
    copying papis\tui\__init__.py -> build\lib\papis\tui
    creating build\lib\papis\tui\widgets
    copying papis\tui\widgets\command_line_prompt.py -> build\lib\papis\tui\widgets
    copying papis\tui\widgets\list.py -> build\lib\papis\tui\widgets
    copying papis\tui\widgets\__init__.py -> build\lib\papis\tui\widgets
    running install_lib
    running install_data
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\svlasov\AppData\Local\Temp\pip-install-j3i5hbfq\papis\setup.py", line 134, in <module>
        platforms=['linux', 'osx'],
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python37\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python37\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "c:\python37\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'etc/bash_completion.d/' cannot end with '/'

    ----------------------------------------
Command "c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\svlasov\\AppData\\Local\\Temp\\pip-install-j3i5hbfq\\papis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\svlasov\AppData\Local\Temp\pip-record-l509184s\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\svlasov\AppData\Local\Temp\pip-install-j3i5hbfq\papis\
```

Any suggestions? Or it just does not support windows yet?

```
> pip --verstion
pip 19.0.3 from c:\python37\lib\site-packages\pip (python 3.7)
```

**Comment by alejandrogallo** [comment]
Hello @stasvlasov ,

sadly papis does not support windows, although there shouldn't be any reason for it not to work
under windows.

I don't have a windows machine to test it. However you can install ubuntu on windows or cygwin,
and papis does work under those environments.

If you test papis under pure windows and make it work, I'd be glad to hear back from you.
Cheers

**Comment by alejandrogallo** [comment]
I made the `setup.py` compatible to windows, I still don't know if it will work, but at least it will not
fail at the `setup.py` stage. Could you try it out ?

**Comment by stasvlasov** [comment]
Works!!! Thank you a lot @alejandrogallo! It installs all well on Windows 10. From elevated cmd (i.e., run as admin) I did the following:
```bat
    rem run the following from cmd.exe as admin

    rem Install Chocolatey:
    @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

    rem install Node.js
    choco install nodejs -y
  
    rem Install current version of papis
    pip install git+https://github.com/papis/papis
```

However, there are some problems with adding papers from url. (Adding just pdfs to the library works fine.) When I do something like:

```bat
papis add --from-url https://arxiv.org/abs/1712.03134
```

It gives me the following error:

```
INFO:cli:add:Attempting to retrieve from url
INFO:downloader:Using downloader 'arxiv'
INFO:downloaders:arxiv:downloading file...
INFO:downloader:Saving downloaded file in C:\Users\svlasov\AppData\Local\Temp\tmpgm41vx0e
INFO:add:run:Got an automatic folder name
INFO:add:run:The folder name is f053b6b8e55c6e98f00aeaddc43a4f5e-xue-lu-and-niall-ada
INFO:add:run:Checking if this document is already in the library
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\python37\lib\site-packages\papis\docmatcher.py", line 62, in return_if_match
    for parsed in cls.parsed_search:
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\Scripts\papis-script.py", line 11, in <module>
    load_entry_point('papis==0.8.2', 'console_scripts', 'papis')()
  File "c:\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\papis\commands\add.py", line 725, in cli
    link=link
  File "c:\python37\lib\site-packages\papis\commands\add.py", line 339, in run
    found_document = papis.utils.locate_document_in_lib(tmp_document)
  File "c:\python37\lib\site-packages\papis\utils.py", line 382, in locate_document_in_lib
    docs = db.query_dict({k: document[k]})
  File "c:\python37\lib\site-packages\papis\database\cache.py", line 233, in query_dict
    return self.query(query_string)
  File "c:\python37\lib\site-packages\papis\database\cache.py", line 243, in query
    return filter_documents(docs, query_string)
  File "c:\python37\lib\site-packages\papis\database\cache.py", line 94, in filter_documents
    papis.docmatcher.DocMatcher.return_if_match, documents
  File "c:\python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
TypeError: 'NoneType' object is not iterable
```

Any ideas if it is fixable?

**Comment by wbrandenburger** [comment]
Servus,

a deeper discussion of the described problem:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\python37\lib\site-packages\papis\docmatcher.py", line 62, in return_if_match
    for parsed in cls.parsed_search:
TypeError: 'NoneType' object is not iterable
"""
```
can be found in [Issue 182](https://github.com/papis/papis/issues/182)

**Comment by alejandrogallo** [comment]
Papis installs now on windows
