### ISSUE TITLE
re.error: multiple repeat at position 2

### ISSUE THREAD

**Issue by teto** [papis/papis#166]
I am using 804f6bb7ee36af1097fefc7e5be59ef67c3fdd6c and I get

```
$ papis -vv open
362-DEBUG:db:cache:Querying
362-DEBUG:db:cache:Getting documents from cache in /home/teto/.cache/papis/database/5b95a1a2ce149bd9e72f01dab58fd37e-papis_db
375-DEBUG:db:cache:Loaded documents (1092 documents)
388-DEBUG:query_parser:Parsing search
389-DEBUG:query_parser:Parsed query = [['*']]
402-DEBUG:filter:Filtering 1092 docs (search '*') using 4 cores
402-DEBUG:filter:pool started
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/teto/papis/papis/docmatcher.py", line 69, in return_if_match
    match = doc if cls.matcher(doc, search, sformat) else None
  File "/home/teto/papis/papis/database/cache.py", line 133, in match_document
    return re.match(regex, match_string, re.IGNORECASE)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/sre_parse.py", line 654, in _parse
    source.tell() - here + len(this))
re.error: multiple repeat at position 2
"""

```
not sure what this is about.

NB: I saw that you moved much stuff to plugin style :D

**Comment by teto** [comment]
With a request like `papis -vv open` it works fine.

**Comment by alejandrogallo** [comment]
hi, somehow I can't reproduce the problem, but I guess you're using the all selector of whoosh
for the papis database, and the queries for the papis database are actually regular expressions in general. So I guess that's the problem `*` as a regultar expression has no meaning, what happens if you do
```
papis open . 
```
?

**Comment by alejandrogallo** [comment]
About the plugins, yes, it's great, you've changed completely papis and made it much better, I hope it continues like this. I will update the roadmap for version v0.9, i'd like to release soon v0.9 so that the scripts can be updated as well.
