### ISSUE TITLE
python_format.format(**{doc: document}) fails with missing keys

### ISSUE THREAD

**Issue by teto** [papis/papis#167]
We should better handle errors when a key is not available:
for instance I have `ref-format = {doc[author_list][0][surname]}{doc[year]}` which triggered:

```
INFO:cli:update:Try using doi 10.1109/ICC.2018.8422950
Traceback (most recent call last):
  File "/run/user/1000/tmp.arEYFH6UA4/bin/papis", line 11, in <module>
    load_entry_point('papis', 'console_scripts', 'papis')()
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8vb16vb9d27171gxxzzsljlpvsgpdmy6-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/teto/papis/papis/commands/update.py", line 367, in cli
    doidata = papis.crossref.doi_to_data(query)
  File "/home/teto/papis/papis/crossref.py", line 188, in doi_to_data
    results = get_data(dois=[doi])
  File "/home/teto/papis/papis/crossref.py", line 172, in get_data
    for d in docs
  File "/home/teto/papis/papis/crossref.py", line 172, in <listcomp>
    for d in docs
  File "/home/teto/papis/papis/crossref.py", line 127, in crossref_data_to_papis_data
    papis.config.get("ref-format"), new_data
  File "/home/teto/papis/papis/utils.py", line 94, in format_doc
    return python_format.format(**{doc: document})
KeyError: 'surname'
```
I can fix it but should I replace missing keys with for instance "surname_notset" ?

**Comment by teto** [comment]
I would be tempted to remove jinja2 from the core as well. It doesn't seem fondamental (jinja2 is not a dependency) and would be best left as a plugin.

**Comment by alejandrogallo** [comment]
I agree about jinja2, it overcomplifies everything, I don't know anymore why I put it there.
