### ISSUE TITLE
papis add --from-bibtex fails with IndexError

### ISSUE THREAD

**Issue by gaalcaras** [papis/papis#171]
I'm trying to import a reference with a .bibtex file:

```
@book{yates1993control,
  title={Control Through Communication: The Rise of System in American Management},
  author={Yates, J.A.},
  isbn={9780801846137},
  lccn={gb94024568},
  series={ACLS Humanities E-Book},
  url={https://books.google.fr/books?id=RaeJbtZFP0EC},
  year={1993},
  publisher={Johns Hopkins University Press}
}
```
But running
```
papis add --from-bibtex ~/Downloads/Control_Through_Communication.bibtex
```
returns the following error:
```
Traceback (most recent call last):
  File "/bin/papis", line 11, in <module>
    load_entry_point('papis==0.8.2', 'console_scripts', 'papis')()
  File "/usr/lib/python3.7/site-packages/papis/main.py", line 10, in main
    papis.commands.default.run()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/papis/commands/add.py", line 672, in cli
    link=link
  File "/usr/lib/python3.7/site-packages/papis/commands/add.py", line 285, in run
    out_folder_name = papis.utils.format_doc(name, temp_doc)
  File "/usr/lib/python3.7/site-packages/papis/utils.py", line 94, in format_doc
    return python_format.format(**{doc: document})
IndexError: string index out of range
```

**Comment by alejandrogallo** [comment]
Hi @gaalcaras , 

this is weird, I can't reproduce the error, specially since I have never tested papis with python3.7
however I'll look into it, it shouldn't be a problem to import from bibtex.

Until I find some time for this, you can try exporting it to yaml
```
papis explore bibtex path/to/bib export --yaml bib.yaml 
papis add --from-yaml bib.yaml
```
I hope this gets you out of trouble for now and can move on with your life ;P

Cheers

**Comment by teto** [comment]
that's the same error I've had in my previous issue, see https://github.com/papis/papis/pull/168 for a fix

**Comment by gaalcaras** [comment]
> that's the same error I've had in my previous issue, see #168 for a fix

Yep, that's it, the fix solves it.

Thanks!
