### ISSUE TITLE
Keep getting an error adding a local file with --from doi option

### ISSUE THREAD

**Issue by capaldo** [papis/papis#230]
After running:
```bash
papis -l ML add ~/Downloads/data_paper.pdf --from doi 10.1038/sdata.2014.32
```

I get the following error after trying to add all:
```bash
INFO:cli:add:Got files ['/var/folders/xx/3qcqnrxj7md526g3lvyld9680000gn/T/tmp4ano7vzy'] from importer doi
Use this file? (Y/n): Y
INFO:add:run:Got an automatic folder name
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papis/commands/add.py", line 554, in cli
    link=link)
  File "/usr/local/lib/python3.7/site-packages/papis/commands/add.py", line 310, in run
    papis.config.get_lib_dirs()[0],
IndexError: list index out of range
```

**Comment by alejandrogallo** [comment]
Hello @capaldo, did you configure the library ML?
Can I see your relevant section in the `~/.config/papis/config` config file?

**Comment by capaldo** [comment]
> Hello @capaldo, did you configure the library ML?
> Can I see your relevant section in the `~/.config/papis/config` config file?

```config
[ML]
dir = /Volumes/pouch/papiers/ML
use-cache = False
add-open = False
```

**Comment by capaldo** [comment]
Just saw that I had a misspelling. Sorry about that.
