### ISSUE TITLE
zotero import raises "AttributeError: module 'papis.api' has no attribute 'get_lib'"

### ISSUE THREAD

**Issue by henningninneh** [papis/papis#246]
I installed papis 09. via pip on FreeBSD 10. When trying to import references from an existing Zotero library into papis, I get the following error:

> AttributeError: module 'papis.api' has no attribute 'get_lib'

Command line input and full error message below: 
```

[henning@localhost ~/cloud/misc/papers]$ papis zotero import ~/henning_wine/Zotero/zotero.sqlite
Traceback (most recent call last):
  File "/usr/local/bin/papis-zotero", line 11, in <module>
    load_entry_point('papis-zotero==0.0.3', 'console_scripts', 'papis-zotero')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/papis_zotero/__init__.py", line 14, in main
    logger.info("library '{0}'".format(papis.api.get_lib()))
AttributeError: module 'papis.api' has no attribute 'get_lib'

```

The same error appears even when entering just `papis zotero import` without specifying a file.

**Comment by EelVex** [comment]
I had the same problem. pip seems to install a previous, incompatible, version of pip-zotero (where `get_lib_name` was `get_lib`). 

Cloning and using

     python3 setup.py install

seems to work.

**Comment by supersambo** [comment]
I'm experiencing the same issue. Installing it from the github version unfortunately does not solve it.

**Comment by ttxtea** [comment]
Seems to be also an issue with `papis --version` 0.11.1.

Starting
~~~
papis -l mylib zotero serve
~~~
raises
~~~
logger.info("library '{0}'".format(papis.api.get_lib()))
AttributeError: module 'papis.api' has no attribute 'get_lib'

~~~
