### ISSUE TITLE
Can't add files with spaces in path

### ISSUE THREAD

**Issue by deeuu** [papis/papis#253]
First, thanks for this awesome tool!

I'm using version 0.9 of`papis`, but the utility function `get_matching_importer_or_downloader` yields 

`http.client.InvalidURL: URL can't contain control characters. '/abs/<path with spaces in>' (found at least ' ')`

when trying `papis add` a file whose path includes spaces.

I understand that spaces can be a headache in general, but I'm importing from a Calibre library so would rather not have to script the whole thing....

Perhaps `pass` the exception, or avoid the call if the path is not suitable for the subsequent `arxiv` stuff?

Thanks again.

**Comment by alejandrogallo** [comment]
Hi, I can't reproduce this, it should actually work. On master this looks like this

https://asciinema.org/a/GIuWddnMNMnmAEh825ehcctLd

**Comment by j-c-w** [comment]
Hi both,

On master, I get an error as reported (commit 6449fcb8), although the error is different than the one @deeuu sees. Reproducion instructions for the error I encounetered doing this below:
```
$ touch "a file"
$ papis add a\ file --set title "A File"
```

Config file is:

```
[papers]
dir = ~/Documents/test

[settings]
default-library = papers
database-backend = whoosh
whoosh-schema-fields = ['year', 'author', 'publisher', 'pages', 'group', 'ref']
opentool = qpdfview --unique
editor = vim


```
And the crash I get is:

```
INFO:importer:bibtex:Reading input file = a file
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 11, in <module>
    load_entry_point('papis==0.9', 'console_scripts', 'papis')()
  File "/home/jackson/.local/lib/python3.6/site-packages/click/core.py"
, line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jackson/.local/lib/python3.6/site-packages/click/core.py"
, line 717, in main
    rv = self.invoke(ctx)
  File "/home/jackson/.local/lib/python3.6/site-packages/click/core.py"
, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jackson/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)                    
  File "/home/jackson/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)                                  
  File "/mnt/ubuntu/Projects/Python/papis/papis/commands/add.py", line
526, in cli
    for f in files), [])
  File "/mnt/ubuntu/Projects/Python/papis/papis/commands/add.py", line
526, in <genexpr>
    for f in files), [])
  File "/mnt/ubuntu/Projects/Python/papis/papis/utils.py", line 235, in get_matching_importer_or_downloader                                  
    matching_string)  # type: Optional[papis.importer.Importer]       
  File "/mnt/ubuntu/Projects/Python/papis/papis/yaml.py", line 97, in match
    importer.fetch()
  File "/mnt/ubuntu/Projects/Python/papis/papis/importer.py", line 135, in wrapper
    fun(self)
  File "/mnt/ubuntu/Projects/Python/papis/papis/yaml.py", line 103, in
fetch
    self.ctx.data = yaml_to_data(self.uri, raise_exception=False)     
  File "/mnt/ubuntu/Projects/Python/papis/papis/yaml.py", line 61, in yaml_to_data
    assert isinstance(data, dict)
AssertionError

```

**Comment by deeuu** [comment]
Sorry for the poor response time.

I can confirm that this is no longer an issue after installing from `master`.

I think that the `AssertionError` reported by @j-c-w is due to the file being empty (or having no MIME type), and not due to the name itself (you can reproduce this using both `touch "afile"` and `touch "a file"`)

Many thanks.
