### ISSUE TITLE
ERROR: tests.downloaders.test_sciencedirect (unittest.loader._FailedTest)

### ISSUE THREAD

**Issue by Earnestly** [papis/papis#271]
Currently attempting to build `papis` from https://github.com/papis/papis/commit/b2de2520bfb57447d6f5343a95ab7aec37505dab

With python 3.8.2 after running `python setup.py build` I use `python setup.py test` but get the following result:

```
test_sciencedirect (unittest.loader._FailedTest) ... ERROR
tests.downloaders.test_sciencedirect (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_sciencedirect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_sciencedirect
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/earnest/build/staging/papis-git/src/papis/tests/downloaders/test_sciencedirect.py", line 2, in <module>
    from papis.downloaders.sciencedirect import Downloader, get_author_list
ImportError: cannot import name 'get_author_list' from 'papis.downloaders.sciencedirect' (/home/earnest/build/staging/papis-git/src/papis/papis/downloaders/sciencedirect.py)


======================================================================
ERROR: tests.downloaders.test_sciencedirect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.downloaders.test_sciencedirect
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/earnest/build/staging/papis-git/src/papis/tests/downloaders/test_sciencedirect.py", line 2, in <module>
    from papis.downloaders.sciencedirect import Downloader, get_author_list
ImportError: cannot import name 'get_author_list' from 'papis.downloaders.sciencedirect' (/home/earnest/build/staging/papis-git/src/papis/papis/downloaders/sciencedirect.py)


----------------------------------------------------------------------
Ran 46 tests in 0.751s

FAILED (errors=2)
```

I'm not sure what additional information is needed.

**Comment by alejandrogallo** [comment]
The downloader tests have to be fixed, sadly I did not have time for this yet, if you look at `setup.cfg` you'll see that they're commented out. However they work.
