### ISSUE TITLE
The readme page uses the option `--from-doi`, which doesn't exist

### ISSUE THREAD

**Issue by lucainnocenti** [papis/papis#281]
In the GitHub readme the following example is given:

    papis add --from-doi 10.1090/noti963 --set tags programming rnoti-p434.pdf

However, the option `--from-doi` doesn't seem to exist. From [the online guide](https://papis.readthedocs.io/en/latest/quick_start.html) I see that it should proabably be `--from doi`, which does work.
I see this on v0.10.

On a similar note, the [Importing section of the guide](https://papis.readthedocs.io/en/latest/importing.html) gives the following command to install the script to import from zotero sqlite:

    wget -O ~/.config/papis/scripts/papis-zotero-sql https://raw.githubusercontent.com/alejandrogallo/papis/master/examples/scripts/papis-zotero-sql

But that file [is not in the repo](https://github.com/papis/papis/tree/ec9cf34cd168d130d4ad31bd04aa6d668ef29405/examples/scripts) (at least not in that location). Also, the link at the end of that section of the guide points to [a nonexisting issue](https://github.com/alejandrogallo/papis/issues/18). Did the method to import from zotero change since the guide was written?

**Comment by alejandrogallo** [comment]
Hello luca,

thank you very much for reporting this.

You're totally right, the online guide and the documentation
are quite outdated, I have updated them now and it should be quite
understandable but of course far from perfect.

Maybe you can check it out now. In principle now the zotero
importing is done by a separate package
that you can find in

  https://github.com/papis/papis-zotero

I have updated also the documentation there.

Sorry for the confusion.

**Comment by lucainnocenti** [comment]
thanks a lot for the prompt reply and fix (and for developing and maintaining the project itself!).

As another minor comment, if I may: the documentation suggests to install `papis` running `pip` via `sudo`. Is there a particular reason for requiring sudo here? It was my understanding that it is not recommended to install packages via `sudo pip`, see e.g. [here](https://askubuntu.com/a/871758/157358) and [here](https://stackoverflow.com/q/15028648/4063051).

**Comment by lucainnocenti** [comment]
the instructions on [`papis-zotero`](https://github.com/papis/papis-zotero) seem to be still outdated. Running `papis zotero import --from-sql path/to/zotero.sqlite` throws an `AttributeError`:

```
Traceback (most recent call last):
  File "/home/aa/miniconda3/bin/papis-zotero", line 8, in <module>
    sys.exit(main())
  File "/home/aa/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aa/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aa/miniconda3/lib/python3.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/home/aa/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aa/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aa/miniconda3/lib/python3.7/site-packages/papis_zotero/__init__.py", line 14, in main
    logger.info("library '{0}'".format(papis.api.get_lib()))
AttributeError: module 'papis.api' has no attribute 'get_lib'
```

**Comment by jorsn** [comment]
In the manual, the first example for the bibtex command still uses `--from-doi` and also `cmd` which both don't exist:

> ```
> papis bibtex                            \
>   read new_papers.bib                   \ # Read bib file
>   cmd 'papis add --from-doi {doc[doi]}'   # For every entry run the command
> ```
> — https://papis.readthedocs.io/en/latest/commands.html#id3

I didn't figure out on first sight (and then didn't search further) how I would import a bibtex database. I think this is very important for a first-time user, so it should be in the readme. At least I am not very interested in setting metadata manually, but very much interested in importing bibtex.

**Comment by alejandrogallo** [comment]
I agree, right now you can import from bibtex using papis-zotero 

https://papis.readthedocs.io/en/latest/importing.html

But probably it would be easier for first-time user to do something like

```
papis bibtex read ./path/to/my/bibfile.bib import
```

Instead of installing `papis-zotero` etc

Right?

**Comment by jorsn** [comment]
The command seems reasonable and simple. I cannot judge overall command consistency. Maybe it would be better integrated into `papis add`.

At least the need for `papis-zotero` to import bibtex should be prominently declared íf it is needed, and `papis-zotero` maybe renamed to `papis-bibtex`. But since papis supports reading bibtex and importing single bibtex entries (`papis add --from bibtex`), I see no reason why it should not import a whole bibtex library.

**Comment by alejandrogallo** [comment]
I just implemented this, importing a bib file into papis, so that one does not have to install `papis-zotero`
maybe you can give it a go ?

```
papis read my-bibfile.bib import --all -o where/to/export
```

**Comment by jghauser** [comment]
@alejandrogallo  I've just tried tried to run the above command, but it doesn't seem to exist (in master).

```
❯ papis read olson_test_export.bib import --all -o Papis_test                           
ERROR:multicommand:did you mean rename?
WARNING:multicommand:I suppose you meant: 'rename'
Usage: papis read [OPTIONS] [QUERY]

Error: no such option: --all
```

**Comment by alejandrogallo** [comment]
Yes, that's because I made a typo writing it, it should be a subcommand of `bibtex`, i.e.

```
papis bibtex read my-bibfile.bib import --all -o where/to/export
```

sorry about that

You can check all the subcommands of bibtex by doing

```
papis bibtex -h
```

or of import

```
papis bibtex import -h
```

**Comment by jghauser** [comment]
Thanks, it works now (and has no issues dealing with multiple attached files)!

**Comment by supersambo** [comment]
I'm getting the `Error: no such option: --all` when running the above command: `papis bibtex read my-bibfile.bib import --all -o where/to/export`

I'm running `papis, version 0.11.1`

**Comment by alejandrogallo** [comment]
Hello, sadly "papis bibtex import" is not available in
version 0.11.1, is right now only available on master,
it will be available in version 0.12, which I could release soon
it was added in commit 4b11caa.

Do you normally install from master or from pip?
I could release v0.12 this weekend since this feature is quite important
in general to people

**Comment by supersambo** [comment]
I understand. No hurry, I'm at the moment only just familiarizing with papis trying to get my zotero library correctly imported.  

In terms of installation I've actually tried both...

**Comment by alexfikl** [comment]
The README was rewritten a while back and there are no more outdated references in it AFAIK.
