### ISSUE TITLE
unhandled and unprecise exception if the config file/library does not exist

### ISSUE THREAD

**Issue by jorsn** [papis/papis#283]
* papis version 0.10

Papis should handle the case where no config file exists correctly. Also, it
should handle the exception that the library does not exist and not annoy users with a traceback.

If I enter `papis` without having created a config file, papis does not complain
about this. Instead, it fails with

```
Traceback (most recent call last):
  File "/nix/store/c6h07agybzvhlmra3abkg520mg13l8jb-python3.8-papis-0.10/bin/.papis-wrapped", line 9, in <module>
    sys.exit(run())
  File "/nix/store/8wbzlvyxw29dhm4ysvrm9jci31jlsmwh-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8wbzlvyxw29dhm4ysvrm9jci31jlsmwh-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nix/store/8wbzlvyxw29dhm4ysvrm9jci31jlsmwh-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/nix/store/8wbzlvyxw29dhm4ysvrm9jci31jlsmwh-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8wbzlvyxw29dhm4ysvrm9jci31jlsmwh-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/c6h07agybzvhlmra3abkg520mg13l8jb-python3.8-papis-0.10/lib/python3.8/site-packages/papis/commands/default.py", line 242, in run
    raise Exception("Library '{0}' does not have any existing folders"
Exception: Library 'papers' does not have any existing folders attached to it, please define and create the paths
```

The error message indicates the wrong problem. The library `papers` is not
defined at all, since there is no config file *and that is the problem.*

So papis creates the config file with a default folder configured for the
`papers` library. And then it is surprised that the folder does not exist?

I would

1. either not create the config file and ask the user to do so,
2. or create the config file and ask the user to modify it, maybe open it directly
   in `$EDITOR`/`$VISUAL`.

I would not automatically create any library folders.

**Comment by alexfikl** [comment]
Hopefully this is no longer an issue. We've made a lot of changes around supporting a lack of config and around initializing (see `papis init`).
