### ISSUE TITLE
AttributeError: module 'papis' has no attribute 'document'

### ISSUE THREAD

**Issue by JP-Ellis** [papis/papis#285]
I was in the process of updating the PKGBUILD for papis on AUR to version 0.11, but it appears to be not working:

```
❯ PAPIS_DEBUG=1 papis
5-DEBUG:config:importing
Traceback (most recent call last):
  File "/usr/bin/papis", line 33, in <module>
    sys.exit(load_entry_point('papis==0.11', 'console_scripts', 'papis')())
  File "/usr/bin/papis", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/papis/commands/default.py", line 36, in <module>
    import papis.api
  File "/usr/lib/python3.8/site-packages/papis/api.py", line 7, in <module>
    import papis.utils
  File "/usr/lib/python3.8/site-packages/papis/utils.py", line 17, in <module>
    import papis.downloaders
  File "/usr/lib/python3.8/site-packages/papis/downloaders/__init__.py", line 11, in <module>
    import papis.bibtex
  File "/usr/lib/python3.8/site-packages/papis/bibtex.py", line 14, in <module>
    import papis.document
  File "/usr/lib/python3.8/site-packages/papis/document.py", line 11, in <module>
    import papis.yaml
  File "/usr/lib/python3.8/site-packages/papis/yaml.py", line 32, in <module>
    def exporter(documents: List[papis.document.Document]) -> str:
AttributeError: module 'papis' has no attribute 'document'
zsh: exit 1     PAPIS_DEBUG=1 papis --help
```

**Comment by alejandrogallo** [comment]
Oh my gott, sorry about that, python3.8 was having a circular
dependency error with `papis.yaml`.

I just fixed and released `v0.11.1`, let me know if it works out that way.

Thanks JP

**Comment by prataffel** [comment]
Hey. Thanks for providing papis. With your changes in e152b55, I fear you broke ``Document.load()``. Importing papis.yaml there as well should fix it.

**Comment by alejandrogallo** [comment]
thanks @prataffel , I just pushed it
