### ISSUE TITLE
Exception: Library 'papers' does not have any existing folders attached to it, please define and create the paths

### ISSUE THREAD

**Issue by MaxenceGiraud** [papis/papis#287]
Just installed lastest version of papis (v0.11.1)  on a ubuntu based distrib and got this error :

```
Traceback (most recent call last):
  File "/home/max/.local/bin/papis", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/max/.local/lib/python3.8/site-packages/papis/commands/default.py", line 242, in run
    raise Exception("Library '{0}' does not have any existing folders"
Exception: Library 'papers' does not have any existing folders attached to it, please define and create the paths

```

**Comment by alejandrogallo** [comment]
Hello, probably the error message should be better. There is a default library named papers with a default location in 
```
~/Documents/papers
```
You will have to either create this folder or change the default folder. I hope this helps
