### ISSUE TITLE
error when setting dmenu as picktool

### ISSUE THREAD

**Issue by sondrec** [papis/papis#290]
I have cloned the newest repository of papis and papis-demenu and compiled from source.
> papis, version 0.11.1

Unfortunately setting dmenu as picktool do not work. 
```
Command:
`papis --log INFO --set picktool dmenu open`
>Traceback (most recent call last):
  File "/usr/local/bin/papis", line 11, in <module>
    load_entry_point('papis==0.11.1', 'console_scripts', 'papis')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/papis-0.11.1-py3.8.egg/papis/commands/open.py", line 183, in cli
    documents = [d for d in papis.pick.pick_doc(documents)]
  File "/usr/local/lib/python3.8/dist-packages/papis-0.11.1-py3.8.egg/papis/pick.py", line 80, in pick_doc
    return pick(documents,
  File "/usr/local/lib/python3.8/dist-packages/papis-0.11.1-py3.8.egg/papis/pick.py", line 56, in pick
    return picker()(options,
TypeError: pick() missing 1 required positional argument: 'options'
```
Any help is appreciated!

**Comment by alejandrogallo** [comment]
Yes, `papis-dmenu` was outdated to the current version of papis, I fixed the issue
and posted a note in search for an active
maintainer since I normally use the terminal/emacs interface and rarely the
dmenu interface.

https://pypi.org/project/papis-dmenu/0.3/

Version 0.3 works now with papis v0.11
Maybe you can confirm it if you've got time ;)

**Comment by sondrec** [comment]
Hi,

It works now! Thank you.

**Comment by alejandrogallo** [comment]
Perfect! I'll close this issue then!
