### ISSUE TITLE
problem removing files from library

### ISSUE THREAD

**Issue by rhaynes74** [papis/papis#300]
Hi folks, it seems like I have messed something up.  I have no directories or files inside my library location, but the following command gives:

papis list --all
/Users/rhaynes/Documents/papers/e8b64a954efd25b6a2a41744cca47455

but

papis rm --all --file
Are you sure? (Y/n): Y
INFO:cli:rm:Removing /Users/rhaynes/Documents/papers/e8b64a954efd25b6a2a41744cca47455/pic1.jpg...
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/papis/commands/rm.py", line 110, in cli
    run(document, filepath=filepath, git=git)
  File "/usr/local/lib/python3.9/site-packages/papis/commands/rm.py", line 33, in run
    os.remove(filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rhaynes/Documents/papers/e8b64a954efd25b6a2a41744cca47455/pic1.jpg'

How do I proceed?

**Comment by alejandrogallo** [comment]
apparently in the file

```
'/Users/rhaynes/Documents/papers/e8b64a954efd25b6a2a41744cca47455/pic1.jpg'

```

does not appear to exist, and you are trying to remove
all the files of all papis documents (is this what you're
trying to do ?)


In this case I would recommend to
resolve the problem manually, you can open the directory
of the document by

```
papis open -d
```

and resolve the issue in the `info.yaml` file.

Remember to clear the database cache whenever you resolve
issues manually, so that papis knows that it should
reindex your documents

```
papis --clear-cache
```


I hope this helps you

**Comment by rhaynes74** [comment]
Hi - many thanks, this cleared up the issue!
