### ISSUE TITLE
error adding local file with space in name

### ISSUE THREAD

**Issue by lebedov** [papis/papis#307]
* papis version (`$ papis --version` or commit number): 0.11.1
# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
cat > foo\ bar.txt <<EOF
This is a file
EOF
papis --log INFO add foo\ bar.txt 2>&1 | tee log
cat log
Traceback (most recent call last):
  File "/Users/lebedov/miniconda3/bin/papis", line 8, in <module>
    sys.exit(run())
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/papis/commands/add.py", line 532, in cli
    matching_importers = sum((
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/papis/commands/add.py", line 533, in <genexpr>
    papis.utils.get_matching_importer_or_downloader(f)
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/papis/utils.py", line 233, in get_matching_importer_or_downloader
    importer = importer_cls.match(
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/papis/arxiv.py", line 287, in match
    validate_arxivid(uri)
  File "/Users/lebedov/miniconda3/lib/python3.8/site-packages/papis/arxiv.py", line 115, in validate_arxivid
    urllib.request.urlopen(request)
  File "/Users/lebedov/miniconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/lebedov/miniconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/lebedov/miniconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/lebedov/miniconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/lebedov/miniconda3/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/lebedov/miniconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/lebedov/miniconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/lebedov/miniconda3/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/Users/lebedov/miniconda3/lib/python3.8/http/client.py", line 1100, in putrequest
    self._validate_path(url)
  File "/Users/lebedov/miniconda3/lib/python3.8/http/client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/abs/./foo bar.txt' (found at least ' ')
```

This seems similar to https://github.com/papis/papis/issues/253, but as noted above, I'm using papis 0.11.1 (on MacOS 10.15.7 with Python 3.8.6 installed via conda).

**Comment by alejandrogallo** [comment]
True, this was sadly the arxiv importer trying to match the path with a url, which then failed raising an `http` exception
saying that the `url` was malformed. I just fixed this.
