### ISSUE TITLE
[Sugestion] Add ability to merge entries

### ISSUE THREAD

**Issue by xmalbertox** [papis/papis#340]
* papis version (`$ papis --version` or commit number):
papis, version 0.11.1

### Problem
As mentioned by @alejandrogallo in #317, sometimes the same item gets added twice, either due to a typo in the title, or from different sources, etc... (one example attached)
![image](https://user-images.githubusercontent.com/11772286/135530965-f957c6dc-fe26-47c1-b3d5-38392bd9d671.png)

As far as i can tell there is no (easy) way of merging two entries, you can add, update, move, or remove only.
Using [FZF](https://github.com/junegunn/fzf) as a picker i can select multiple entries for editing but it then opens each one sequentially, so there's no easy way to diff the two files.

### Suggestion

Provide a way to mark multiple entries for merging then the user could see a diff, or choose a pre-configured behaviour (like keep newest, or merge missing parts, etc...) or manually fix any problems and choose an entry to keep.
I think it would a great addition to what is becoming a very powerful and flexible reference manager.

**Comment by alejandrogallo** [comment]
That is actually a good idea, I just pushed a tentative implementation. Now you can also pick several items
with the papis picker, so you do not need necessarily the `fzf` picker for this, you can just press `ctrl-t` to tag
the elements you want.

If you checkout the master branch, you can checkout the `papis merge -h` command.
I'll be testing during the next weeks, but in principle it should be readable and it should work.

Cheers!

**Comment by xmalbertox** [comment]
Hi, 

Thanks for taking the time, I just tested the latest master and i get the following errors when i try to use _papis merge_ both with the default picker (the keybinding for marking is working as expected), and the fzf picker.


> Traceback (most recent call last):
  File "/usr/bin/papis", line 33, in <module>
    sys.exit(load_entry_point('papis==0.11.1', 'console_scripts', 'papis')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/papis/commands/merge.py", line 117, in cli
    data_b.pop("files")
KeyError: 'files'

My configuration is here in case it helps:
https://pastebin.com/V9i0QzY2

**Comment by alejandrogallo** [comment]
Hi! 

I actually answered this but it got deleted.
Sorry for that, that was my bad.
I fixed it and now I added a flag `--out`
so that you can write out the merged document in a folder
and can inspect for testing first, withouth modifing your database.

Cheers!

**Comment by xmalbertox** [comment]
Hello,

I tested most of the flags for the merge command (except __--git__) and everything is working perfectly. This will be very useful, I have quite a few of duplicates remnant from when i did my initial import from zotero.

Thank you!
