### ISSUE TITLE
Installed under Python3.11.0a7 then it failed to start

### ISSUE THREAD

**Issue by chenle02** [papis/papis#397]
* papis version (`$ papis --version` or commit number):
After updating my system python from 3.8 to 3.11.0a7,  I installed pipas again under the new python version. But I cannot start papis anymore.
# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/configparser.py", line 804, in get
    value = d[option]
            ~^^^^^^^^
  File "/usr/local/lib/python3.11/collections/__init__.py", line 992, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/collections/__init__.py", line 984, in __missing__
    raise KeyError(key)
    ^^^^^^^^^^^^^^^^^^^
KeyError: 'default-library'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/papis", line 33, in <module>
    sys.exit(load_entry_point('papis==0.12', 'console_scripts', 'papis')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/papis", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/papis/commands/default.py", line 38, in <module>
    import papis.api
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/api.py", line 8, in <module>
    import papis.utils
    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/utils.py", line 19, in <module>
    import papis.downloaders
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/downloaders/__init__.py", line 6, in <module>
    import papis.bibtex
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/bibtex.py", line 20, in <module>
    ] + papis.config.getlist('extra-bibtex-types')  # type: List[str]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 457, in getlist
    rawvalue = general_get(key, section=section)  # type: Any
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 362, in general_get
    config = get_configuration()
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 486, in get_configuration
    local_config_file = papis.config.get("local-config-file")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 407, in get
    return general_get(key, section=section)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 363, in general_get
    libname = get_lib_name()
              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 581, in get_lib_name
    return get_lib().name
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/papis/config.py", line 600, in get_lib
    lib = config.get(papis.config.get_general_settings_name(),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 807, in get
    raise NoOptionError(option, section)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
configparser.NoOptionError: No option 'default-library' in section: 'settings'


```

**Comment by dornhe** [comment]
I have a similar issue but with python 3.10.6 under arch-linux.

**Comment by dornhe** [comment]
Solved

Afte some (way too much) time, I finally read the error correctly: You need to add 'default-library' in your config file. 
In the section [settings]just do as [in the documentation](https://papis.readthedocs.io/en/latest/configuration.html#) and it will work.

**Comment by alexfikl** [comment]
I was just about to suggest that! It still sounds like a bug though, because `papis` should have a fallback for these options in
https://github.com/papis/papis/blob/b3247777d3afad2f326aeecdf7dd179b24e6e007/papis/config.py#L82-L87
so it shouldn't outright crash.

**Comment by chenle02** [comment]
Thank dornhe for your great debugging~! It works now~!

**Comment by dornhe** [comment]
> I was just about to suggest that! It still sounds like a bug though, because `papis` should have a fallback for these options in
> 
> https://github.com/papis/papis/blob/b3247777d3afad2f326aeecdf7dd179b24e6e007/papis/config.py#L82-L87
> 
> so it shouldn't outright crash.

I agree. The solution has more the character of an 'hot-fix'

**Comment by alexfikl** [comment]
@dornhe Gave fixing this a try in #400. Let me know if you get a chance to test it and it works for you too! (it looks reasonable enough)
