### ISSUE TITLE
Upgrade to version 1.12 and failed to start

### ISSUE THREAD

**Issue by chenle02** [papis/papis#398]
* papis version (`$ papis --version` or commit number):
In the previous issue, I installed the latest Python 3.11.0a7 (ubuntu machine) and failed to start papis. Now I switched to another Ubuntu machine where I have my native python3.8. What I did is `pip3 install --upgrade papis`
# how to reproduce the issue
Command and output of `papis --log INFO <command>`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'default-library'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lechen/.local/bin/papis", line 5, in <module>
    from papis.commands.default import run
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/commands/default.py", line 38, in <module>
    import papis.api
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/api.py", line 8, in <module>
    import papis.utils
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/utils.py", line 19, in <module>
    import papis.downloaders
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/downloaders/__init__.py", line 6, in <module>
    import papis.bibtex
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/bibtex.py", line 20, in <module>
    ] + papis.config.getlist('extra-bibtex-types')  # type: List[str]
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 457, in getlist
    rawvalue = general_get(key, section=section)  # type: Any
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 362, in general_get
    config = get_configuration()
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 486, in get_configuration
    local_config_file = papis.config.get("local-config-file")
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 407, in get
    return general_get(key, section=section)
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 363, in general_get
    libname = get_lib_name()
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 581, in get_lib_name
    return get_lib().name
  File "/home/lechen/.local/lib/python3.8/site-packages/papis/config.py", line 600, in get_lib
    lib = config.get(papis.config.get_general_settings_name(),
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'default-library' in section: 'settings'
```

**Comment by chenle02** [comment]
After rolling back to Version 0.11.1, I can still use my papis now. But it would be good to fix the issues in order to use the new features. Thanks a lot~!

**Comment by alexfikl** [comment]
This wasn't an issue with the python version, but rather with the `papis` version and some recent-ish changes. Should also be fixed by #400. 

If you get a chance to test the `git` version prior to the next release and see if it's actually fixed, that would be great!
