### ISSUE TITLE
use-cache option broken

### ISSUE THREAD

**Issue by nico202** [papis/papis#47]
setting `use-cache = False` (either in settings or in library)

❯papis check
         
```                                                                                                                                                                           ~
Traceback (most recent call last):
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/bin/.papis-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/main.py", line 24, in main
    papis.commands.main()
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/commands/__init__.py", line 236, in main
    commands["default"].main()
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/commands/default.py", line 167, in main
    commands[self.args.command].main()
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/commands/check.py", line 46, in main
    self.get_args().search
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/api.py", line 216, in get_documents_in_lib
    return papis.api.get_documents_in_dir(directory, search)
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/api.py", line 197, in get_documents_in_dir
    return papis.utils.get_documents(directory, search)
  File "/nix/store/mfgz8nf4a1i35had90zxii4cx8dpy9v2-papis-0.5.2/lib/python3.6/site-packages/papis/utils.py", line 298, in get_documents
    folders = get_folders()
TypeError: get_folders() missing 1 required positional argument: 'folder'
```

**Comment by nico202** [comment]
Also the cache system is quite ineffective.
On an SSD deleting the cache folder leads to a `papis list` command time of 
> cpu 1.395 total  

while by using the cache it takes

> cpu 1.376 total

Results are quite consistent

**Comment by alejandrogallo** [comment]
Yes you're right, do to this and since the webapp will be coming, 
I decided that first of all a clear structure of the database was needed and implementing
a whoosh based database would be a first step towards getting rid of the very primitve
cache system.

I'm currently working on this in the `database` branch, soon to be merged with whoosh support.
Hopefully this will make everything faster and cleaner to be able to implement other backends such as
`xapian`.
