### ISSUE TITLE
Cannot find \Lib\Subprocess

### ISSUE THREAD

**Issue by ChemistKieran** [papis/papis#477]
* papis version (0.12):

# how to reproduce the issue
Command and output of `papis --log INFO add https://arxiv.org/abs/1712.03134':
```
INFO:cli:add:Got files ['C:\\Users\\XYR\\AppData\\Local\\Temp\\tmpk7os__9r'] from importer 'arxiv'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\papis.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\papis\commands\add.py", line 562, in cli
    papis.utils.open_file(f)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\papis\utils.py", line 87, in open_file
    general_open(file_name=file_path, key="opentool", wait=wait)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\papis\utils.py", line 69, in general_open
    subprocess.call(cmd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Hi, I'm having an issue where I get the above error when running several commands such as add.
I'm running on windows 10, Python Version 3.11.

Thanks!

**Comment by alexfikl** [comment]
That sounds like an issue with your Python installation. Can you check that something simple like this works:
```
python -c 'import subprocess; print(subprocess.DEVNULL)'
```
?

**Comment by ChemistKieran** [comment]
Thanks, 
Yes. 
when I run the above it returns:
 
`-3`

**Comment by alexfikl** [comment]
> Thanks, Yes. when I run the above it returns:
> `-3`

Hm, that seems to indicate that python works and it can find its libraries. Thank you for checking that!
So it would seem to be an issue with the command that `papis` is launching. First, can you check that something simple like
```
papis config default-library
```
works? If yes, running with debug information would be very helpful, i.e. run
```
papis --log DEBUG add 'https://arxiv.org/abs/1712.03134'
```
and look for a debug log message going something like `cmd: start filename`? Feel free to attach the full log here too, so we can look through it. My thought is that your `opentool` may not be configured correctly (see [the docs](https://papis.readthedocs.io/en/latest/configuration.html#config-settings-opentool)), which would also throw a similar error.

I apologize for this being a bit tedious, but I'm not a Windows user and can't test much myself :(

**Comment by alexfikl** [comment]
From a bit of googling: https://stackoverflow.com/a/49709965.

Can you also try
```
papis --set opentool 'cmd /c start' add 'https://arxiv.org/abs/1712.03134'
```
? (assuming that syntax is correct)

**Comment by ChemistKieran** [comment]
Yes, that worked great - thank you!

I ended up putting the following in the config file:
(launching via msedge, but it works well without - displaying a choose a program dialog box)

`opentool = cmd /c start msedge`
