### ISSUE TITLE
encoding issues on windows

### ISSUE THREAD

**Issue by l-spiecker** [papis/papis#567]
* papis, version 0.13

# how to reproduce the issue
Command and output of `papis add --from doi https://doi.org/10.1111%2Ffebs.15572 spage2vec-unsupervised-representation-of-localized-spatial-gene-expression-signatures/the-febs-journal-2020-partel-spage2vec-unsupervised-representation-of-localized-spatial-gene-expression-signatures.pdf`:

```
[INFO] utils: Merging data from importer 'doi'.
- author:
- author_list:
- citations:
- doc_url:
- doi:
+ author: Partel, Gabriele and Wählby, Carolina
+ author_list: [{'given': 'Gabriele', 'family': 'Partel', 'affiliation': [{'name': 'Centre for Image Analysis Department of Information Technology and SciLifeLab Uppsala University Uppsala Sweden'}]}, {'given': 'Carolina', 'family': 'Wählby', 'affiliation': [{'name': 'Centre for Image Analysis Department of Information Technology and SciLifeLab Uppsala University Uppsala Sweden'}]}]
+ citations: [{'doi': '10.1038/nprot.2017.149'}, {'doi': '10.1016/j.cell.2015.10.039'}, {'doi': '10.7554/eLife.27041'}, {'doi': '10.1016/j.neuron.2016.10.001'}, {'doi': '10.1126/science.aat5691'}, {'doi': '10.1126/science.aau5324'}, {'doi': '10.1038/s41592-018-0175-z'}, {'doi': '10.1038/s41586-019-1049-y'}, {'author': 'Park J', 'journal-title': 'bioRxiv', 'year': '2019', 'article-title': 'Segmentation‐free inference of cell types from in situ transcriptomics data'}, {'doi': '10.1214/aoms/1177704472'}, {'doi': '10.1038/s41592-019-0631-4'}, {'doi': '10.1038/nbt.4260'}, {'doi': '10.1038/nm.3394'}, {'doi': '10.1098/rstb.2006.2016'}, {'doi': '10.1073/pnas.162041399'}, {'doi': '10.1126/science.aad0501'}, {'doi': '10.1074/jbc.R700043200'}, {'doi': '10.1038/nrm3918'}, {'doi': '10.1016/j.neuron.2012.02.036'}, {'doi': '10.1038/nrm2548'}, {'doi': '10.1126/science.1176488'}, {'doi': '10.1016/j.conb.2019.01.016'}, {'doi': '10.1016/S0896-6273(02)00978-9'}, {'doi': '10.1016/j.neuron.2012.05.033'}, {'doi': '10.1016/j.cell.2011.11.064'}, {'doi': '10.1016/j.gde.2011.04.002'}, {'volume-title': 'Advances in Neural Information Processing Systems', 'author': 'Hamilton W', 'year': '2017', 'first-page': '1024'}, {'author': 'Wu Z', 'first-page': '1', 'journal-title': 'IEEE Trans Neural Netw Learn Syst', 'year': '2020', 'article-title': 'A comprehensive survey on graph neural networks'}, {'doi': '10.1126/science.aaa6090'}, {'doi': '10.1093/bioinformatics/btaa541'}, {'author': 'Veličković P', 'journal-title': 'arXiv', 'year': '2017', 'article-title': 'Graph attention networks'}, {'unstructured': 'MaasAL HannunAY&NgAY(2013)Rectifier nonlinearities improve neural network acoustic models. InProc.icml30 3.http://robotics.stanford.edu/~amaas/papers/relu_hybrid_icml2013_final.pdf'}, {'author': 'Kingma DP', 'journal-title': 'arXiv', 'year': '2014', 'article-title': 'A method for stochastic optimization'}, {'author': 'McInnes L', 'journal-title': 'arXiv', 'year': '2018', 'article-title': 'Umap: Uniform manifold approximation and projection for dimension reduction'}, {'doi': '10.1038/s41598-019-41695-z'}, {'doi': '10.1186/s13059-017-1382-0'}, {'doi': '10.1038/s41598-018-28948-z'}]
+ doc_url: https://onlinelibrary.wiley.com/doi/pdf/10.1111/febs.15572
+ doi: 10.1111/febs.15572
- issue:
+ issue: 6
?        +
- journal:
+ journal: The FEBS Journal
- language:
+ language: en
?           ++
- month:
+ month: 3
?        +
- pages:
+ pages: 1859--1870
- publisher:
+ publisher: Wiley
?            +++++
- title:
- type:
- url:
+ title: Spage2vec: Unsupervised representation of localized spatial gene expression signatures
+ type: article
+ url: http://dx.doi.org/10.1111/febs.15572
- volume:
+ volume: 288
?         +++
- year:
+ year: 2021
?       ++++
^^^^^^^^^
diff from
-----  -
+++++ Importer(doi, uri=https://doi.org/10.1111%2Ffebs.15572)

Add all[a] Split[s] Reject[n] Quit[q] Cancel[c]
--- Diff view: all changes ---
[INFO] commands.add: Created reference 'Spage2vecUnsuPartel2021'.
[INFO] commands.add: Document folder is 'C:\Users\USERNAME\workspace\BIB\papers\spage2vec-unsupervised-representation-of-localized-spatial-gene-expression-signatures-a'.
Traceback (most recent call last):
  File "C:\Users\USERNAME\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USERNAME\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\USERNAME\.local\bin\papis.exe\__main__.py", line 7, in <module>
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\commands\add.py", line 638, in cli
    run(ctx.files,
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\commands\add.py", line 415, in run
    tmp_document.save()
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\document.py", line 331, in save
    papis.yaml.data_to_yaml(self.get_info_file(), dict(self))
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\yaml.py", line 30, in data_to_yaml
    yaml.dump(
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\__init__.py", line 253, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\__init__.py", line 241, in dump_all
    dumper.represent(data)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\representer.py", line 28, in represent
    self.serialize(node)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\serializer.py", line 98, in serialize_node
    self.serialize_node(item, node, index)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\serializer.py", line 107, in serialize_node
    self.serialize_node(key, node, None)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\serializer.py", line 89, in serialize_node
    self.emit(ScalarEvent(alias, node.tag, implicit, node.value,
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\emitter.py", line 115, in emit
    self.state()
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\emitter.py", line 412, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\emitter.py", line 1132, in write_plain
    self.stream.write(data)
  File "C:\Users\USERNAME\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2010' in position 12: character maps to <undefined>
```

# Issue doesn't appears on wsl, but then open fails on windows:

```
papis open
[INFO] database.cache: Indexing library. This might take a while...
Error reading info file at 'C:\Users\USERNAME\workspace\BIB\papers\spage2vec-unsupervised-representation-of-localized-spatial-gene-expression-signatures-a\info.yaml'. Please check it!
Traceback (most recent call last):
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\yaml.py", line 61, in yaml_to_data
    data = yaml.load(fd, Loader=Loader)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml\_yaml.pyx", line 668, in yaml._yaml.CParser.get_single_node
  File "yaml\_yaml.pyx", line 858, in yaml._yaml.CParser._parse_next_event
  File "yaml\_yaml.pyx", line 867, in yaml._yaml.input_handler
  File "C:\Users\USERNAME\Miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 714: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\document.py", line 341, in load
    data = papis.yaml.yaml_to_data(info_file, raise_exception=True)
  File "C:\Users\USERNAME\.local\pipx\venvs\papis\lib\site-packages\papis\yaml.py", line 64, in yaml_to_data
    raise ValueError(exc) from exc
ValueError: 'charmap' codec can't decode byte 0x90 in position 714: character maps to <undefined>
[WARNING] commands.open: No documents retrieved
```

Possible Solution: Passing encoding in papis/yaml.py > load open() call and also encode everything fine during save.

**Comment by alexfikl** [comment]
@l-spiecker #571 Tries to use that metadata and can write/read the YAML files correctly now. Can you try it out and see if it fixes the issue for you?

Thank you for reporting these issues on Windows by the way! papis doesn't get a lot of testing there and it's very useful :heart:

**Comment by l-spiecker** [comment]
Sorry for answering so late. The error disappeared now. Thanks, nice work!

**Comment by alexfikl** [comment]
> Sorry for answering so late. The error disappeared with this fix. Thanks, nice work!

No worries! Thanks for checking back in and testing!

There seem to be some issues in the tests (with `mypy` and `click`), but as soon as those are cleared up, I'll go ahead and merge the fix and close this!
