### ISSUE TITLE
Papis is messing with Bibtex reference strings

### ISSUE THREAD

**Issue by bellebaum** [papis/papis#643]
I noticed that papis is changing some references in my bibtex files and resetting them.
Concretely, I believe it is ignoring an existing reference when parsing the bibtex file.

* papis version (`papis --version`): `papis, version 0.13`

# how to reproduce the issue

1. Import a document and explicitly specify the reference string. This is one I tested:

```
$ papis add --from doi "10.17487/RFC6749" --folder-name "rfc6749" --set ref "rfc6749" --batch
```

2. Add it to a bib file:

```
$ papis bibtex  add -q 6749 save bibliography.bib
$ cat bibliography.bib
@report{rfc6749,
  author = {},
  doi = {10.17487/rfc6749},
  month = {10},
  publisher = {RFC Editor},
  title = {The OAuth 2.0 Authorization Framework},
  url = {http://dx.doi.org/10.17487/rfc6749},
  year = {2012},
}
```

So far, this is what I expected. It correctly used `rfc6749` as the reference string.
Things do go wrong however once I use `bibtex doctor` or add another entry.
I have distilled the issue down to what should be mere copying:

```
$ papis bibtex read bibliography.bib save bibliography2.bib
$ diff bibliography{,2}.bib
1,2c1
< @report{rfc6749,
<   author = {},
---
> @report{TheOauth20A2012,
```

## Additional Information

`papis --log INFO <command>` does not show anything special, so here is `--log DEBUG` for the "copying":

<details>
<summary>Click to expand logs</summary>

```
$ papis --log DEBUG bibtex read bibliography3.bib save bibliography2.bib 
[INFO] bibtex: Reading BibTeX file 'bibliography3.bib'...
[DEBUG] bibtex: Reading in file: 'bibliography3.bib'.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/papis/document.py", line 120, in keyconversion_to_data
    new_value = action(papis_value)
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/papis/bibtex.py", line 226, in <lambda>
    "action": lambda author: papis.document.split_authors_name([
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/papis/document.py", line 197, in split_authors_name
    given = " ".join(parts["first"])
                     ~~~~~^^^^^^^^^
KeyError: 'first'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/papis/logging.py", line 73, in format
    return super().format(record)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not enough arguments for format string
Call stack:
  File "/usr/bin/papis", line 33, in <module>
    sys.exit(load_entry_point('papis==0.13', 'console_scripts', 'papis')())
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/papis/bibtex.py", line 200, in explorer
    for d in bibtex_to_dict(bibfile)]
  File "/usr/lib/python3.11/site-packages/papis/bibtex.py", line 269, in bibtex_to_dict
    return [bibtexparser_entry_to_papis(entry) for entry in entries]
  File "/usr/lib/python3.11/site-packages/papis/bibtex.py", line 269, in <listcomp>
    return [bibtexparser_entry_to_papis(entry) for entry in entries]
  File "/usr/lib/python3.11/site-packages/papis/bibtex.py", line 232, in bibtexparser_entry_to_papis
    result = papis.document.keyconversion_to_data(
  File "/usr/lib/python3.11/site-packages/papis/document.py", line 122, in keyconversion_to_data
    logger.debug("Error while trying to parse '%s' (%s).",
Message: "Error while trying to parse '%s' (%s)."
Arguments: ('author_list',)
[INFO] bibtex: Found 1 documents.
Are you sure you want to save? (Y/n):
[INFO] commands.bibtex: Saving 1 documents in 'bibliography2.bib'.
[DEBUG] plugin: Creating manager for namespace 'papis.format'.
[DEBUG] format: Using 'python' formater.
[DEBUG] bibtex: Generated ref 'The OAuth 2.0 A  2012'.
[DEBUG] bibtex: Using ref 'TheOauth20A2012'.
[DEBUG] bibtex: Processing BibTeX entry: 'doi: 10.17487/rfc6749'.
[DEBUG] bibtex: Processing BibTeX entry: 'month: 10'.
[DEBUG] bibtex: Processing BibTeX entry: 'publisher: RFC Editor'.
[DEBUG] bibtex: Processing BibTeX entry: 'title: The OAuth 2.0 Authorization Framework'.
[DEBUG] bibtex: Processing BibTeX entry: 'url: http://dx.doi.org/10.17487/rfc6749'.
[DEBUG] bibtex: Processing BibTeX entry: 'year: 2012'.
```

</details>

It is struggling with the author's list (and in fact, the authors are missing in the copy), but this might be a separate issue? I am not sure.

Thanks in advance for any help :)

**Comment by alejandrogallo** [comment]
I confirm this is a bug, thank you for reporting.
Weird that I did not notice before.

So the problem was that at readtime the conversion of the bibtexitem
into a papis entry was ignoring the reference of the bibtex entry,
in the following function


```python
def bibtexparser_entry_to_papis(entry: Dict[str, Any]) -> Dict[str, Any]:
    """Convert the keys of a BibTeX entry parsed by :mod:`bibtexparser` to a
    papis-compatible format.

    :param entry: a dictionary with keys parsed by :mod:`bibtexparser`.
    :returns: a dictionary with keys converted to a papis-compatible format.
    """
    from bibtexparser.latexenc import latex_to_unicode

    _k = papis.document.KeyConversionPair
    print(entry)
    key_conversion = [
        # before _k("ID", [{"key": "ref", "action": lambda x: None}]),
        _k("ID", [{"key": "ref", "action": None}]),
        # ^------------------------------------------
        _k("ENTRYTYPE", [{"key": "type", "action": None}]),
        _k("link", [{"key": "url", "action": None}]),
        _k("title", [{
            "key": "title",
            "action": lambda x: latex_to_unicode(x.replace("\n", " "))
            }]),
        _k("author", [{
            "key": "author_list",
            "action": lambda author: papis.document.split_authors_name([
                latex_to_unicode(author)
                ])
            }]),
    ]

    ...
```

I think I can push the fix, I looked at the git-blame of this function and apparently the
last person touching it was me in 2020, so I think I just made a mistake here
and it's safe to fix

**Comment by alejandrogallo** [comment]
Right now I don't see an obvious solution for the problem of having a bibtex
entry with an empty author field.

Is it relevant to have an empty author field and preserve its emptyness writing the bibfile ?

**Comment by alejandrogallo** [comment]
Perfect, thank you for the heads up! I'll close this then.
