### ISSUE TITLE
update --all?

### ISSUE THREAD

**Issue by michaelplews** [papis/papis#77]
## Problem
Updates and added functionality to the documents objects cause some entries to become outdated. Notably, commit eca5709 brought us citation information https://github.com/papis/papis/blob/eca57093deaafbb4d0cbea7f22788ebf2782c65e/papis/crossref.py#L181-L197 
meaning all references in my library before August 3rd 2017 don't have this citation information. I can update these references individually using `papis update ref=[REF] --from-doi '[DOI]'` but that takes a lot of time if I have 100+ entries.

## Solution
It would be nice to have a `papis update --all --from-doi` (or other flag) to allow the entire library to be updated via crossref with any new information able to be extracted, such as citations.

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

A possibly related issue is https://github.com/papis/papis/issues/31 (Update database model to allow for whoosh backend).

**Comment by michaelplews** [comment]
Possibly related:

``papis update ref=Dhanapala2017a --auto``

gives

```
ERROR:Command:urllib failed to download
ERROR:downloaders:acs:Retrieving urls does not work for acs yet
Traceback (most recent call last):
  File "/usr/local/bin/papis", line 11, in <module>
    load_entry_point('papis==0.6', 'console_scripts', 'papis')()
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/main.py", line 24, in main
    sys.exit(papis.commands.main())
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/commands/__init__.py", line 236, in main
    return commands["default"].main()
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/commands/default.py", line 160, in main
    return commands[self.args.command].main()
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/commands/update.py", line 213, in main
    from_doi=self.args.from_doi
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/commands/update.py", line 57, in run
    url_data = papis.downloaders.utils.get(from_url)
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/downloaders/utils.py", line 108, in get
    doc_data = downloader.get_document_data()
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/downloaders/base.py", line 118, in get_document_data
    self.download_document()
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/downloaders/base.py", line 131, in download_document
    url = self.get_document_url()
  File "/usr/local/lib/python3.5/dist-packages/papis-0.6-py3.5.egg/papis/downloaders/acs.py", line 47, in get_document_url
    raise Exception
Exception
```

however 
`papis update ref=Dhanapala2017a --from-doi='10.1021/acs.inorgchem.7b02075' `

works as expected. This should not be different, as https://github.com/papis/papis/blob/a10ce1ebac0c9231ff2e0b4fc33916739766fd84/papis/commands/update.py#L184-L185

sets the document doi to --from-doi by default. Example .yaml is attached
[Dhanapala2017a.txt](https://github.com/papis/papis/files/2091031/Dhanapala2017a.txt)
