### ISSUE TITLE
"TypeError: object of type 'filter' has no len()" when using explore

### ISSUE THREAD

**Issue by bluehood** [papis/papis#96]
Here's the command and the error:

```
~/Downloads papis explore arxiv --author 'Forster' pick export --bibtex /tmp/p.yml                                                                                      (py3) 
INFO:explore:arxiv:Looking up...
INFO:explore:arxiv:20 documents found
Traceback (most recent call last):
  File "/home/blue/miniconda2/envs/py3/bin/papis", line 11, in <module>
    sys.exit(main())
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/papis/main.py", line 22, in main
    papis.commands.default.run()
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/blue/miniconda2/envs/py3/lib/python3.6/site-packages/papis/commands/explore.py", line 475, in export
    len(docs),
TypeError: object of type 'filter' has no len()
```

**Comment by alejandrogallo** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.
